# Generated by Django 5.1.2 on 2024-10-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='instagram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='telegram',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
