# Generated by Django 5.1.2 on 2024-10-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_product_instagram_product_telegram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='product',
            name='telegram',
        ),
        migrations.AddField(
            model_name='contact',
            name='instagram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='telegram',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
