# Generated by Django 5.1.2 on 2024-10-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='telegram',
            field=models.URLField(blank=True),
        ),
    ]
